import type { Locale } from '@/i18n/utils';

/**
 * MINEFECT product catalogue — single typed source of truth.
 * Generated by merging the legacy catalog.js (FR) + catalog-en.js (EN) by id.
 * 7 categories · 12 subcategories · 43 products.
 */
export type Unit = 'PCE' | 'KG' | 'M';

export interface Product {
  id: string;
  name: { fr: string; en: string };
  description: { fr: string; en: string };
  image: string;
  unit: Unit;
  ref?: string;
}
export interface Subcategory {
  id: string;
  title: { fr: string; en: string };
  products: Product[];
}
export interface Category {
  id: string;
  title: { fr: string; en: string };
  description: { fr: string; en: string };
  image: string;
  subcategories: Subcategory[];
}

export const PLACEHOLDER_PRODUCT = '/assets/images/placeholders/product.png';

/** Products with no real photo render a branded placeholder + "Sur demande / On request" label. */
export const isPlaceholder = (p: Product): boolean => p.image === PLACEHOLDER_PRODUCT;

export const t = (v: { fr: string; en: string }, lang: Locale): string => v[lang];

export const CATALOG: Category[] = [
  {
    "id": "equipements-lourds",
    "title": {
      "fr": "Équipements lourds",
      "en": "Heavy equipment"
    },
    "description": {
      "fr": "Marteaux piqueurs, compresseurs, accessoires et pièces d’engins.",
      "en": "Jackhammers, compressors, accessories and machine parts."
    },
    "image": "/assets/images/categories/equipements-lourds.png",
    "subcategories": [
      {
        "id": "marteaux-piqueurs",
        "title": {
          "fr": "Marteaux piqueurs & accessoires",
          "en": "Jackhammers & accessories"
        },
        "products": [
          {
            "id": "jackhammer",
            "name": {
              "fr": "Marteau piqueur",
              "en": "Pneumatic jackhammer"
            },
            "description": {
              "fr": "Marteau piqueur pneumatique robuste pour démolition et travaux de roche, conçu pour une cadence élevée et une maintenance simplifiée sur site.",
              "en": "Heavy-duty pneumatic jackhammer for demolition and rock work, designed for high production rates and easy on-site maintenance."
            },
            "image": "/assets/images/products/marteau-piqueur.png",
            "unit": "PCE",
            "ref": "JACKHAMMER"
          },
          {
            "id": "body-hammer-125-jieshida",
            "name": {
              "fr": "Corps de marteau Jieshida 125",
              "en": "Jieshida 125 hammer body"
            },
            "description": {
              "fr": "Corps (carter) pour marteau Jieshida 125, conçu pour résister aux chocs et assurer un guidage stable des organes internes.",
              "en": "Body/casing for Jieshida 125 hammer, built to withstand impacts and ensure stable guidance of internal components."
            },
            "image": "/assets/images/products/corps-marteau-jieshida-125.png",
            "unit": "PCE",
            "ref": "BODY HAMMER 125 JIESHIDA"
          },
          {
            "id": "piston",
            "name": {
              "fr": "Piston",
              "en": "Piston"
            },
            "description": {
              "fr": "Piston de rechange pour marteau piqueur, usiné pour garantir l’énergie d’impact et préserver le rendement de l’outil.",
              "en": "Replacement piston for jackhammer, machined to maintain impact energy and preserve overall tool efficiency."
            },
            "image": "/assets/images/products/piston.png",
            "unit": "PCE",
            "ref": "PISTON"
          },
          {
            "id": "bague-piston-za",
            "name": {
              "fr": "Bague de piston (ZA)",
              "en": "Piston bushing (ZA)"
            },
            "description": {
              "fr": "Bague de piston (ZA) pour guidage et tenue mécanique de l’ensemble mobile, contribuant à réduire l’usure et les jeux.",
              "en": "Piston bushing (ZA) for guidance and mechanical support of the moving assembly, helping reduce wear and play."
            },
            "image": "/assets/images/products/bague-piston-za.png",
            "unit": "PCE",
            "ref": "BOULAGE ZA PISTON"
          },
          {
            "id": "bague-zo-mugitwe",
            "name": {
              "fr": "Bague (ZO Mugitwe)",
              "en": "Bushing (ZO Mugitwe)"
            },
            "description": {
              "fr": "Bague (ZO) destinée à l’assemblage et à la maintenance, avec référence d’origine conservée pour assurer la compatibilité.",
              "en": "Bushing (ZO) for assembly and maintenance; original reference kept to ensure compatibility."
            },
            "image": "/assets/images/products/bague-zo-mugitwe.png",
            "unit": "PCE",
            "ref": "BOULAGE ZO MUGITWE"
          },
          {
            "id": "porte-bobine-jieshida-125",
            "name": {
              "fr": "Porte-bobine Jieshida 125",
              "en": "Jieshida 125 brush holder"
            },
            "description": {
              "fr": "Porte-bobine (porte-charbons) pour Jieshida 125, assurant un maintien fiable des balais et un bon contact électrique.",
              "en": "Brush/coil holder (brush holder) for Jieshida 125, ensuring secure brush retention and reliable electrical contact."
            },
            "image": "/assets/images/products/porte-bobine-jieshida-125.png",
            "unit": "PCE",
            "ref": "PORTE BOBINE /JIESHIDA 125"
          },
          {
            "id": "burins-longs",
            "name": {
              "fr": "Burins longs pour marteau piqueur",
              "en": "Long chisels for jackhammer"
            },
            "description": {
              "fr": "Burins longs pour marteau piqueur, acier traité pour une meilleure tenue à l’usure et une pénétration efficace en chantier.",
              "en": "Long chisels for jackhammers; heat-treated steel for improved wear resistance and effective penetration on site."
            },
            "image": "/assets/images/products/burins-longs.png",
            "unit": "PCE",
            "ref": "CHISELS /JACKHAMMERS /LONG"
          },
          {
            "id": "burins-b47",
            "name": {
              "fr": "Burins pour B47",
              "en": "Chisels for B47"
            },
            "description": {
              "fr": "Burins compatibles B47, adaptés aux travaux de percement/démolition, avec géométrie et trempe pensées pour l’endurance.",
              "en": "B47-compatible chisels for drilling/demolition work, with geometry and heat treatment designed for durability."
            },
            "image": "/assets/images/products/burins-b47.png",
            "unit": "PCE",
            "ref": "CHISELS FOR B47"
          },
          {
            "id": "burins-tcd-20",
            "name": {
              "fr": "Burins pour TCD 20",
              "en": "Chisels for TCD 20"
            },
            "description": {
              "fr": "Burins compatibles TCD 20, conçus pour une performance régulière et une durée de vie optimisée en conditions abrasives.",
              "en": "TCD 20-compatible chisels designed for consistent performance and optimized lifetime in abrasive conditions."
            },
            "image": "/assets/images/products/burins-tcd-20.png",
            "unit": "PCE",
            "ref": "CHISELS FOR TCD 20"
          }
        ]
      },
      {
        "id": "compresseurs-air",
        "title": {
          "fr": "Compresseurs & pièces B47",
          "en": "B47 compressors & parts"
        },
        "products": [
          {
            "id": "compresseur-b47",
            "name": {
              "fr": "Compresseur B47",
              "en": "B47 compressor"
            },
            "description": {
              "fr": "Compresseur pneumatique B47 pour travaux intensifs sur site, avec conception robuste, pièces disponibles et entretien simplifié.",
              "en": "B47 pneumatic compressor for heavy-duty field work, with robust design, available spares, and simplified maintenance."
            },
            "image": "/assets/images/products/compresseur-b47.png",
            "unit": "PCE",
            "ref": "B 47 COMPRESSOR"
          },
          {
            "id": "b47-tappet-seat",
            "name": {
              "fr": "Siège de poussoir B47",
              "en": "B47 tappet seat"
            },
            "description": {
              "fr": "Siège de poussoir pour B47, pièce d’appui assurant le bon guidage et la régularité du cycle de fonctionnement.",
              "en": "Tappet seat for B47; support component ensuring proper guidance and stable operating cycles."
            },
            "image": "/assets/images/products/siege-poussoir-b47.png",
            "unit": "PCE",
            "ref": "B47 TAPPET SEAT"
          },
          {
            "id": "b47-front-head",
            "name": {
              "fr": "Tête avant B47",
              "en": "B47 front head"
            },
            "description": {
              "fr": "Tête avant compatible B47, support avant assurant le guidage, la protection et la stabilité de l’ensemble en service.",
              "en": "B47-compatible front head, providing guidance, protection and stability of the assembly in operation."
            },
            "image": "/assets/images/products/tete-avant-b47.png",
            "unit": "PCE",
            "ref": "B47 FRONT HEAD"
          },
          {
            "id": "b47-steel-retainer",
            "name": {
              "fr": "Bague de retenue acier B47",
              "en": "B47 steel retainer ring"
            },
            "description": {
              "fr": "Bague de retenue en acier pour assemblage B47, conçue pour maintenir les composants malgré vibrations et chocs.",
              "en": "Steel retainer ring for B47 assembly, designed to hold components under vibration and shock loads."
            },
            "image": "/assets/images/products/bague-retenue-acier-b47.png",
            "unit": "PCE",
            "ref": "B47 STEEL RETAINER"
          },
          {
            "id": "b47-rubber-cover",
            "name": {
              "fr": "Protection caoutchouc B47",
              "en": "B47 rubber cover"
            },
            "description": {
              "fr": "Protection caoutchouc pour B47, limite l’entrée de poussières et amortit les chocs pour prolonger la durée de vie.",
              "en": "Rubber cover for B47; reduces dust ingress and dampens impacts to extend service life."
            },
            "image": "/assets/images/products/protection-caoutchouc-b47.png",
            "unit": "PCE",
            "ref": "B47 RUBBER COVER"
          }
        ]
      },
      {
        "id": "dents-accessoires",
        "title": {
          "fr": "Pointes & accessoires d’engins",
          "en": "Tips & machine accessories"
        },
        "products": [
          {
            "id": "pointe-1u3352rc-pin-lock",
            "name": {
              "fr": "Pointe 1U3352RC + goupille de verrouillage",
              "en": "1U3352RC tip + locking pin"
            },
            "description": {
              "fr": "Pointe type 1U3352RC avec goupille de verrouillage, conçue pour résister à l’abrasion et sécuriser le montage sur dents.",
              "en": "1U3352RC-type tip with locking pin, built for abrasion resistance and secure mounting on teeth."
            },
            "image": "/assets/images/products/pointe-1u3352rc-pin-lock.png",
            "unit": "PCE",
            "ref": "TIPS/1U3352RC+PIN LOCK"
          },
          {
            "id": "moteur-dumper",
            "name": {
              "fr": "Moteur de dumper",
              "en": "Dumper engine"
            },
            "description": {
              "fr": "Moteur de dumper (selon modèle), solution de remplacement pour maintenir la disponibilité de l’engin; sélection sur référence.",
              "en": "Dumper engine (model-dependent). Replacement solution to maintain equipment availability; selected by reference."
            },
            "image": "/assets/images/products/moteur-dumper.png",
            "unit": "PCE",
            "ref": "MOTEUR DUMPER"
          }
        ]
      }
    ]
  },
  {
    "id": "pieces-consommables",
    "title": {
      "fr": "Pièces & consommables",
      "en": "Spare parts & consumables"
    },
    "description": {
      "fr": "Filtres, roulements, courroies, kits d’entretien…",
      "en": "Filters, bearings, belts, maintenance kits…"
    },
    "image": "/assets/images/categories/pieces-consommables.png",
    "subcategories": [
      {
        "id": "electricite-moteurs",
        "title": {
          "fr": "Électricité & moteurs",
          "en": "Electrical & motors"
        },
        "products": [
          {
            "id": "induit-jieshida",
            "name": {
              "fr": "Induit Jieshida",
              "en": "Jieshida armature (rotor)"
            },
            "description": {
              "fr": "Induit (rotor) pour équipements Jieshida, équilibré pour un fonctionnement stable et un couple régulier en charge.",
              "en": "Armature/rotor for Jieshida equipment, balanced for stable operation and consistent torque under load."
            },
            "image": "/assets/images/products/induit-jieshida.png",
            "unit": "PCE",
            "ref": "INDUIT /JIESHIDA"
          },
          {
            "id": "interrupteur",
            "name": {
              "fr": "Interrupteur",
              "en": "Switch"
            },
            "description": {
              "fr": "Interrupteur de remplacement pour outillage/équipement, conçu pour des contacts fiables et une bonne durée de vie.",
              "en": "Replacement switch for tools/equipment, designed for reliable contacts and extended service life."
            },
            "image": "/assets/images/products/interrupteur.png",
            "unit": "PCE",
            "ref": "SWITCH"
          },
          {
            "id": "verrou",
            "name": {
              "fr": "Verrou",
              "en": "Lock"
            },
            "description": {
              "fr": "Verrou de maintien/assemblage, destiné à sécuriser les organes et limiter les jeux en service.",
              "en": "Locking component for retention/assembly to secure parts and minimize play in service."
            },
            "image": "/assets/images/products/verrou.png",
            "unit": "PCE",
            "ref": "LOCK"
          },
          {
            "id": "fil-bobinage-075",
            "name": {
              "fr": "Fil de bobinage 0,75 mm",
              "en": "Rewinding wire 0.75 mm"
            },
            "description": {
              "fr": "Fil de bobinage cuivre émaillé 0,75 mm pour rebobinage moteur, avec isolation adaptée aux contraintes d’atelier.",
              "en": "Enameled copper rewinding wire 0.75 mm for motor rewinding, with insulation suitable for workshop conditions."
            },
            "image": "/assets/images/products/fil-bobinage.png",
            "unit": "KG",
            "ref": "REWINDING WIRE 0.75"
          },
          {
            "id": "fil-bobinage-09",
            "name": {
              "fr": "Fil de bobinage 0,9 mm",
              "en": "Rewinding wire 0.9 mm"
            },
            "description": {
              "fr": "Fil de bobinage cuivre émaillé 0,9 mm pour rebobinage moteur, garantissant une bonne tenue électrique et thermique.",
              "en": "Enameled copper rewinding wire 0.9 mm for motor rewinding, ensuring good electrical and thermal performance."
            },
            "image": "/assets/images/products/fil-bobinage.png",
            "unit": "KG",
            "ref": "REWINDING WIRE 0.9"
          },
          {
            "id": "fil-bobinage-10",
            "name": {
              "fr": "Fil de bobinage 1,0 mm",
              "en": "Rewinding wire 1.0 mm"
            },
            "description": {
              "fr": "Fil de bobinage cuivre émaillé 1,0 mm pour rebobinage et réparation, conforme aux exigences d’isolation et de fiabilité.",
              "en": "Enameled copper rewinding wire 1.0 mm for repairs, meeting insulation and reliability requirements."
            },
            "image": "/assets/images/products/fil-bobinage.png",
            "unit": "KG",
            "ref": "REWINDING WIRE 1"
          }
        ]
      },
      {
        "id": "outillage-electroportatif",
        "title": {
          "fr": "Outillage électroportatif",
          "en": "Power tools"
        },
        "products": [
          {
            "id": "meuleuse-ga9020",
            "name": {
              "fr": "Meuleuse Makita GA9020",
              "en": "Angle grinder 230 mm (GA9020 type)"
            },
            "description": {
              "fr": "Meuleuse d’angle 230 mm type GA9020, idéale pour coupe et ébarbage; puissance élevée et ergonomie adaptée au chantier.",
              "en": "230 mm angle grinder (GA9020 type) for cutting and grinding; high power and site-ready ergonomics."
            },
            "image": "/assets/images/products/meuleuse-ga9020.png",
            "unit": "PCE",
            "ref": "PONCEUSES GA 9020/CUTTING MACHINE"
          },
          {
            "id": "induit-ga9020",
            "name": {
              "fr": "Induit pour meuleuse GA9020",
              "en": "Armature for GA9020 grinder"
            },
            "description": {
              "fr": "Induit de remplacement pour meuleuse type GA9020, équilibrage et isolation conçus pour limiter l’échauffement.",
              "en": "Replacement armature for GA9020-type grinder; balanced and insulated to limit heating."
            },
            "image": "/assets/images/products/induit-ga9020.png",
            "unit": "PCE",
            "ref": "INDUIT/PONCEUSE GA 9020"
          },
          {
            "id": "balais-ga9020",
            "name": {
              "fr": "Balais carbone pour Makita GA9020",
              "en": "Carbon brushes for GA9020"
            },
            "description": {
              "fr": "Jeu de balais carbone pour meuleuse type GA9020, assurant un contact stable, une usure régulière et moins d’étincelles.",
              "en": "Carbon brush set for GA9020-type grinder, ensuring stable contact, consistent wear and reduced sparking."
            },
            "image": "/assets/images/products/balais-ga9020.png",
            "unit": "PCE",
            "ref": "CHARBON PONCEUSE MAKITA GA9020"
          },
          {
            "id": "bride-ga9020",
            "name": {
              "fr": "Bride pour GA9020",
              "en": "Clamp flange for GA9020"
            },
            "description": {
              "fr": "Bride de serrage pour meuleuse type GA9020, garantissant un maintien sûr du disque et une compatibilité avec l’arbre.",
              "en": "Clamping flange for GA9020-type grinder, ensuring safe disc retention and spindle compatibility."
            },
            "image": "/assets/images/products/bride-ga9020.png",
            "unit": "PCE",
            "ref": "BRIDE/PONCEUSEGA9020"
          },
          {
            "id": "pignon-engrenage",
            "name": {
              "fr": "Pignon + engrenage",
              "en": "Pinion + gear set"
            },
            "description": {
              "fr": "Ensemble pignon + engrenage pour transmission (selon machine), usinage précis pour un engrènement régulier et durable.",
              "en": "Pinion + gear set for transmission (machine-dependent), precision machined for smooth and durable meshing."
            },
            "image": "/assets/images/products/pignon-engrenage.png",
            "unit": "PCE",
            "ref": "PIGNON+ENGLENAGE"
          }
        ]
      },
      {
        "id": "roulements-consommables",
        "title": {
          "fr": "Roulements & consommables",
          "en": "Bearings & consumables"
        },
        "products": [
          {
            "id": "roulements-brouette",
            "name": {
              "fr": "Roulements de brouette",
              "en": "Wheelbarrow wheel bearings"
            },
            "description": {
              "fr": "Roulements pour roue de brouette, offrant une rotation fluide et une bonne résistance à la poussière et aux charges.",
              "en": "Bearings for wheelbarrow wheels, providing smooth rotation and good resistance to dust and loads."
            },
            "image": "/assets/images/products/roulements-brouette.png",
            "unit": "PCE",
            "ref": "BEARINGS FOR WHEEL BARROW"
          },
          {
            "id": "balais-carbone-95",
            "name": {
              "fr": "Balais carbone 95",
              "en": "Carbon brushes 95"
            },
            "description": {
              "fr": "Balais carbone (réf. 95) pour moteurs/outillage, conçus pour un bon contact et une usure maîtrisée.",
              "en": "Carbon brushes (ref. 95) for motors/tools, designed for good contact and controlled wear."
            },
            "image": "/assets/images/products/balais-carbone.png",
            "unit": "PCE",
            "ref": "CHARBON 95"
          },
          {
            "id": "balais-carbone-125",
            "name": {
              "fr": "Balais carbone 125",
              "en": "Carbon brushes 125"
            },
            "description": {
              "fr": "Balais carbone (réf. 125) pour moteurs/outillage, assurant une conduction stable et une bonne durée de service.",
              "en": "Carbon brushes (ref. 125) for motors/tools, ensuring stable conduction and good service life."
            },
            "image": "/assets/images/products/balais-carbone.png",
            "unit": "PCE",
            "ref": "CHARBON 125"
          },
          {
            "id": "futs-bidons",
            "name": {
              "fr": "Fûts / bidons (contenants)",
              "en": "Drums / jerrycans (containers)"
            },
            "description": {
              "fr": "Contenants (fûts/bidons) pour stockage et transport de consommables et fluides, avec options selon volume et usage.",
              "en": "Containers (drums/jerrycans) for storage and transport of consumables and liquids, with options by volume and use case."
            },
            "image": "/assets/images/products/futs-bidons.png",
            "unit": "PCE",
            "ref": "CASKS"
          }
        ]
      }
    ]
  },
  {
    "id": "securite-epi",
    "title": {
      "fr": "Sécurité & EPI",
      "en": "Safety & PPE"
    },
    "description": {
      "fr": "Casques, lunettes, gants, harnais, signalisation…",
      "en": "Helmets, glasses, gloves, harnesses, signage…"
    },
    "image": "/assets/images/categories/securite-epi.png",
    "subcategories": [
      {
        "id": "eclairage-site",
        "title": {
          "fr": "Éclairage & signalisation",
          "en": "Lighting & signage"
        },
        "products": [
          {
            "id": "lampe-led-double-flexible",
            "name": {
              "fr": "Lampe LED double flexible",
              "en": "Dual flexible LED lamp"
            },
            "description": {
              "fr": "Lampe LED double flexible pour zones de travail et inspection, à faible consommation et orientation rapide sur site.",
              "en": "Dual flexible LED lamp for work and inspection areas, low power consumption and quick orientation on site."
            },
            "image": "/assets/images/products/lampe-led-double-flexible.png",
            "unit": "PCE",
            "ref": "LED DOUBLE SNAKE LIGHT"
          },
          {
            "id": "signalisation",
            "name": {
              "fr": "Signalisation & balisage",
              "en": "Signage & marking"
            },
            "description": {
              "fr": "Rubalise, cônes, panneaux et accessoires de balisage pour sécuriser les zones à risque et la circulation sur site.",
              "en": "Barrier tape, cones, signs and marking accessories to secure risk areas and manage site traffic."
            },
            "image": "/assets/images/placeholders/product.png",
            "unit": "PCE"
          }
        ]
      }
    ]
  },
  {
    "id": "instrumentation-capteurs",
    "title": {
      "fr": "Instrumentation & capteurs",
      "en": "Instrumentation & sensors"
    },
    "description": {
      "fr": "Surveillance vibratoire, thermique, niveau, pression…",
      "en": "Vibration, temperature, level and pressure monitoring…"
    },
    "image": "/assets/images/categories/instrumentation-capteurs.png",
    "subcategories": [
      {
        "id": "surveillance-mesures",
        "title": {
          "fr": "Surveillance & mesures",
          "en": "Monitoring & measurements"
        },
        "products": [
          {
            "id": "capteur-vibration",
            "name": {
              "fr": "Capteur de vibration",
              "en": "Vibration sensor"
            },
            "description": {
              "fr": "Capteur de vibration pour monitoring conditionnel des machines tournantes, permettant une détection précoce des défauts.",
              "en": "Condition monitoring sensor for rotating machinery, enabling early fault detection and reduced downtime."
            },
            "image": "/assets/images/placeholders/product.png",
            "unit": "PCE"
          },
          {
            "id": "capteur-pression",
            "name": {
              "fr": "Capteur de pression",
              "en": "Pressure sensor"
            },
            "description": {
              "fr": "Capteur de pression industriel pour hydraulique et procédé, offrant une mesure stable en environnement terrain exigeant.",
              "en": "Industrial pressure sensor for hydraulic and process applications, providing stable measurement in harsh environments."
            },
            "image": "/assets/images/placeholders/product.png",
            "unit": "PCE"
          }
        ]
      }
    ]
  },
  {
    "id": "services-techniques",
    "title": {
      "fr": "Services techniques",
      "en": "Technical services"
    },
    "description": {
      "fr": "Maintenance, audits sécurité, optimisation de flotte…",
      "en": "Maintenance, safety audits, fleet optimization…"
    },
    "image": "/assets/images/categories/services-techniques.png",
    "subcategories": [
      {
        "id": "maintenance",
        "title": {
          "fr": "Maintenance & support",
          "en": "Maintenance & support"
        },
        "products": [
          {
            "id": "plan-maintenance",
            "name": {
              "fr": "Plan de maintenance",
              "en": "Maintenance plan"
            },
            "description": {
              "fr": "Élaboration de plans de maintenance préventive (gammes, périodicités, pièces critiques) pour réduire les arrêts et maîtriser les coûts.",
              "en": "Preventive maintenance planning (tasks, intervals, critical spares) to reduce downtime and control costs."
            },
            "image": "/assets/images/placeholders/product.png",
            "unit": "PCE"
          },
          {
            "id": "audit-securite",
            "name": {
              "fr": "Audit sécurité",
              "en": "Safety audit"
            },
            "description": {
              "fr": "Audit HSE terrain avec constats, priorisation des actions et recommandations opérationnelles pour renforcer la conformité.",
              "en": "On-site HSE audit with findings, action prioritization and practical recommendations to strengthen compliance."
            },
            "image": "/assets/images/placeholders/product.png",
            "unit": "PCE"
          }
        ]
      }
    ]
  },
  {
    "id": "reactifs-medias-traitement",
    "title": {
      "fr": "Réactifs & médias de traitement",
      "en": "Reagents & process media"
    },
    "description": {
      "fr": "Réactifs et consommables de procédé pour le traitement des minerais et des eaux : chaux, floculants, charbon actif, médias de broyage…",
      "en": "Process reagents and consumables for ore and water treatment: lime, flocculants, activated carbon, grinding media…"
    },
    "image": "/assets/images/categories/reactifs-medias-traitement.png",
    "subcategories": [
      {
        "id": "reactifs",
        "title": {
          "fr": "Réactifs",
          "en": "Reagents"
        },
        "products": [
          {
            "id": "chaux",
            "name": {
              "fr": "Chaux",
              "en": "Lime"
            },
            "description": {
              "fr": "Chaux industrielle pour régulation du pH, neutralisation et conditionnement de pulpe, avec granulométrie adaptée selon procédé.",
              "en": "Industrial lime for pH control, neutralization and slurry conditioning, with process-adapted particle size."
            },
            "image": "/assets/images/products/chaux.png",
            "unit": "KG"
          },
          {
            "id": "floculant",
            "name": {
              "fr": "Floculant",
              "en": "Flocculant"
            },
            "description": {
              "fr": "Floculant polymère pour épaississement/clarification, améliorant la décantation et la qualité de l’eau recyclée.",
              "en": "Polymer flocculant for thickening/clarification to improve settling and recycled water quality."
            },
            "image": "/assets/images/products/floculant.png",
            "unit": "KG"
          },
          {
            "id": "charbon-actif",
            "name": {
              "fr": "Charbon actif",
              "en": "Activated carbon"
            },
            "description": {
              "fr": "Charbon actif à haute surface spécifique pour adsorption et polissage final, adapté au traitement des eaux et aux applications procédé.",
              "en": "High-surface-area activated carbon for adsorption and final polishing, suitable for water treatment and process applications."
            },
            "image": "/assets/images/products/charbon-actif.png",
            "unit": "KG"
          }
        ]
      },
      {
        "id": "medias-broyage",
        "title": {
          "fr": "Médias de broyage",
          "en": "Grinding media"
        },
        "products": [
          {
            "id": "boulets",
            "name": {
              "fr": "Boulets",
              "en": "Grinding balls"
            },
            "description": {
              "fr": "Boulets de broyage en acier pour broyeurs, disponibles en plusieurs diamètres/duretés pour optimiser l’usure et la performance.",
              "en": "Steel grinding balls for mills, available in various diameters/hardness grades to optimize wear and performance."
            },
            "image": "/assets/images/products/boulets.png",
            "unit": "KG"
          }
        ]
      }
    ]
  },
  {
    "id": "conseil-ingenierie",
    "title": {
      "fr": "Conseil & ingénierie",
      "en": "Consulting & engineering"
    },
    "description": {
      "fr": "Études, dimensionnement, optimisation et accompagnement terrain.",
      "en": "Studies, sizing, optimization and on-site support."
    },
    "image": "/assets/images/categories/conseil-ingenierie.png",
    "subcategories": [
      {
        "id": "etudes",
        "title": {
          "fr": "Études & dimensionnement",
          "en": "Studies & sizing"
        },
        "products": [
          {
            "id": "etude-dimensionnement",
            "name": {
              "fr": "Étude de dimensionnement",
              "en": "Sizing study"
            },
            "description": {
              "fr": "Étude de dimensionnement (débits, charge, contraintes terrain) et note de calcul pour fiabiliser vos choix d’équipement.",
              "en": "Sizing study (flows, loads, site constraints) and calculation note to support robust equipment decisions."
            },
            "image": "/assets/images/placeholders/product.png",
            "unit": "PCE"
          },
          {
            "id": "audit-procedes",
            "name": {
              "fr": "Audit de procédés",
              "en": "Process audit"
            },
            "description": {
              "fr": "Audit de procédés avec diagnostic performance, identification des goulots et plan d’amélioration actionnable.",
              "en": "Process performance audit to identify bottlenecks and deliver an actionable improvement plan."
            },
            "image": "/assets/images/placeholders/product.png",
            "unit": "PCE"
          }
        ]
      }
    ]
  }
];

export const findCategory = (id: string): Category | undefined => CATALOG.find((c) => c.id === id);
export const findSubcategory = (cat: Category, id: string): Subcategory | undefined =>
  cat.subcategories.find((s) => s.id === id);

export const totalProducts = (): number =>
  CATALOG.reduce((a, c) => a + c.subcategories.reduce((b, s) => b + s.products.length, 0), 0);
